[workspace]
authors = ["Riccardo Cappuzzo <riccardo.cappuzzo@gmail.com>"]
channels = ["conda-forge"]
name = "openttd-optim-routes"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.4.1,<3"
pillow = ">=12.1.0,<13"
pandas = ">=3.0.0,<4"
polars = ">=1.37.1,<2"
matplotlib = ">=3.10.8,<4"
opencv = ">=4.13.0,<5"
tqdm = ">=4.67.2,<5"
marimo = ">=0.19.7,<0.20"
wigglystuff = ">=0.2.18,<0.3"
